Feature/1 map
sergkryk/purple_js_advanced pull request #1
Opened 2023-06-22 13:43 UTC by sergkryk

2023-07-18 09:39 UTC, Grinv requested changes

2023-07-18 09:39 UTC, Grinv commented on 1-map/main.js
> +  if (acc.find((a => a.id === el.id))) {
Тут нам нужно всего лишь посмотреть, есть ли у нас в массиве запись с таким id, нам не нужно содержимое. Поэтому я бы применил `some` вместо `find`

2023-07-18 09:39 UTC, Grinv commented on 1-map/main.js
> +  return acc;
```javascript
  if (!acc.some(a => a.id === el.id)) {
     acc.push(el);
  }
  
  return acc;

2023-07-18 09:39 UTC, Grinv commented on 1-map/main.js
> +const uniqueWithSet = Array.from(new Set(arr.map(a => a.id)))
Лучше делать более универсальные функции. Давай сделаем фунцию, в которую передаём массив а на выход получаем уникализированный массив.

2023-07-18 09:39 UTC, Grinv commented on 1-map/main.js
> +const uniqueWithSet = Array.from(new Set(arr.map(a => a.id)))
Написал в задачке с кубиком. Лучше названия функций начинать с глагола
Тут можно назвать например `unifyWithSet`

2023-07-18 09:39 UTC, Grinv commented on 1-map/main.js
Давай попробуем сделать немного с другим условием.
Нам нужно уникализировать массив не по одному полю id, а когда у нас ВСЕ поля дублируются.
Например из такого:
```javascript
const arr = [
  {id: 1, name: "Семён"},
  {id: 1, name: "Вася"},
  {id: 2, name: "Петя"},
  {id: 1, name: "Семён"},
  {id: 3, name: "Антон"},
  {id: 3, name: "Антон"},
  {id: 3, name: "Даша"},
]
```
должны получить такой:
```javascript
const uniqueArr = [
  {id: 1, name: "Семён"},
  {id: 1, name: "Вася"},
  {id: 2, name: "Петя"},
  {id: 3, name: "Антон"},
  {id: 3, name: "Даша"},
]

2023-07-18 10:22 UTC, sergkryk commented on 1-map/main.js
> +  if (acc.find((a => a.id === el.id))) {
Применил

2023-07-18 10:24 UTC, sergkryk commented on 1-map/main.js
> +const uniqueWithSet = Array.from(new Set(arr.map(a => a.id)))
Да, понял. Ну так как здесь не было функции и название делал существительным, передела на функции и поменял имя.

2023-07-18 10:27 UTC, sergkryk commented on 1-map/main.js
> +const uniqueWithSet = Array.from(new Set(arr.map(a => a.id)))
переделал на функции

2023-07-18 11:38 UTC, sergkryk commented on 1-map/main.js
добавил, но решение подсмотрел в одном блоге, вернее функцию сравнения объектов, сам начал копать не туда и как следствие зашёл в тупик

2023-07-20 04:04 UTC, Grinv requested changes

2023-07-20 04:04 UTC, Grinv commented on 1-map/main.js
> +}
Да, как вариант. Но получается очень затратный.
Можно проще :) Попробуй применить связку `JSON.parse`/`JSON.stringify` и `Set` ;)

2023-07-20 17:04 UTC, sergkryk commented on 1-map/main.js
> +}
Наверное понял, залил в реквест

2023-07-25 01:37 UTC, Grinv approved these changes

2023-07-25 01:37 UTC, Grinv commented on 1-map/main.js
> +  return JSON.stringify(obj1) === JSON.stringify(obj2);
Не совсем так. Тебе надо было изначально весь массив объектов обработать через JSON.stringify. Фактически у тебя в каждом элементе будет строка. Потом всё преобразовать в Set, одинаковые строки отсеются. А потом массив обработать через JSON.parse. И всё
Ну ладно, оставим на самостоятельную работу

2023-07-25 05:21 UTC, sergkryk commented on 1-map/main.js
> +  return JSON.stringify(obj1) === JSON.stringify(obj2);
`function getUniqueObjectsV2(arr) {
  return Array.from(new Set(arr.map(el => JSON.stringify(el)))).map(el => JSON.parse(el));
}`

добавил и залил

2023-07-25 05:22 UTC, merged