adds 12-promises-race
sergkryk/purple_js_advanced pull request #10
Opened 2023-08-05 09:52 UTC by sergkryk

2023-08-05 11:31 UTC, Grinv requested changes

2023-08-05 11:31 UTC, Grinv commented on 12-promise-race/main.js
> +  const result = await Promise.race(promises);
Не совсем правильно понял задачу)
Нам нужно представить, что `Promise.race` вообще не существует и нам нужно написать свою собственную реализацию race. Так называемый полифилл.

2023-08-14 05:48 UTC, sergkryk commented on 12-promise-race/main.js
> +  const result = await Promise.race(promises);
переделал

2023-08-14 07:07 UTC, Grinv approved these changes

2023-08-14 07:07 UTC, Grinv commented on 12-promise-race/main.js
> +// оригинальная функция из интернета, не понимаю зачем делать Promise.resolve если у нас и так список промисов у которых есть метод then
Они ещё и заворачивают в промис функцию, которая может не быть промисом. Смысла в этом я особо не вижу. Твоя функция правильно работает.

2023-08-14 07:07 UTC, merged