Feature/10 pokemon promise
sergkryk/purple_js_advanced pull request #11
Opened 2023-08-05 09:53 UTC by sergkryk

2023-08-05 11:28 UTC, Grinv requested changes

2023-08-05 11:28 UTC, Grinv commented on 10-pokemon-promise/main.js
> +getPokemonAbility("ditto", consoleData);
Вся прелесть промисов в том, чтобы избавляться от коллбэков и строить красивые и читабельные цепочки.
Давай так и сделаем и избавимся от коллбэка.
getPokemonAbility ничего не должен знать о коллбэка, он просто возращает промис
getPokemonAbility("ditto").then(consoleData);

Впринципе даже в предыдущем задании можно избавиться от коллбэков. И частенько так делают. Через промисификацию. Можешь попробовать в качестве самостоятельного дз так и сделать с предыдущий)
Почитать можешь тут: https://learn.javascript.ru/promisify

2023-08-13 16:46 UTC, sergkryk commented on 10-pokemon-promise/main.js
> +getPokemonAbility("ditto", consoleData);
избавился

2023-08-14 07:01 UTC, Grinv approved these changes

2023-08-14 07:01 UTC, Grinv commented on 10-pokemon-promise/main.js
> +// я так понимаю дополнительная обертка в виде промиса не нужна т.к. fetch и так возвращает промис
Да, всё верно

2023-08-14 07:01 UTC, merged