adds 3-birthday
sergkryk/purple_js_advanced pull request #2
Opened 2023-07-16 15:53 UTC by sergkryk

2023-07-18 09:18 UTC, Grinv commented on 3-birthday/main.js
> +function isAdult(personBirthday, min_age = 14) {
`min_age` - раз остальные переменные у нас в camelCase написаны, давай и она тоже будет в camelCase

2023-07-18 09:20 UTC, Grinv commented on 3-birthday/main.js
> +}
Да, как вариант подходит.
Можно немного более более красивую и простую логику применить.
Мы можем отнять из одной даты другую и посмотреть, сколько это составляет лет. Подумай, как это можно сделать)

2023-07-18 12:28 UTC, sergkryk commented on 3-birthday/main.js
> +function isAdult(personBirthday, min_age = 14) {
исправлено

2023-07-18 12:43 UTC, sergkryk commented on 3-birthday/main.js
> +}
Отправил второй вариант, но мне он как то не очень т.к. учитывает только год

2023-07-20 04:09 UTC, Grinv requested changes

2023-07-20 04:09 UTC, Grinv commented on 3-birthday/main.js
> +}
Немного другое направление. Ты можешь перевести обе даты в timestamp и узнаешь разницу между ними в миллисекундах. Из этого количества миллисекунд мы уже сможем узнать, сколько лет пользователю и подходит ли он к нужным критериям.

2023-07-20 17:16 UTC, sergkryk commented on 3-birthday/main.js
> +}
Но тогда будет сложнее определять с точностью до дня, а вдруг начинающий алкоголик пришел в день своего рождения. Нужно же високосные года учитывать. Во втором варианте я получаю эту разницу в миллисекундах но ведь не могу ее просто делить diff / 1000 / 60 / 60 / 24 / 365

2023-07-25 02:13 UTC, Grinv requested changes

2023-07-25 02:13 UTC, Grinv commented on 3-birthday/main.js
> +console.log(isAdultV2('1983-06-07'));
Обязательно тестируй на пограничные состояния.
Сегодня 25 июля 2023. Чтоб мне исполнилось 14 в этот день, я должен родиться `2009-07-25`. Давай потестируем
Ожидается результат
`2009-07-24 => true`
`2009-07-25 => true`
`2009-07-26 => false`
По итогу неверный вывод
`2009-07-24 => false`
`2009-07-25 => false`
`2009-07-26 => false`

2023-07-25 02:13 UTC, Grinv commented on 3-birthday/main.js
> +  const birthday = new Date(Number(year), Number(month) + 1, date);
Не понял, зачем к месяцу прибавлять 1? 
Я впрниципе не понял, зачем приводить к строке. Можно ж сразу дату распарсить)
```javascript
const birthday = new Date(personBirthday)

2023-07-25 05:39 UTC, sergkryk commented on 3-birthday/main.js
> +console.log(isAdultV2('1983-06-07'));
> Обязательно тестируй на пограничные состояния.

Ок, первый вариант отлично отрабатывает и в целом не понимаю чем он плох

> Да, как вариант подходит.
Можно немного более более красивую и простую логику применить.
Мы можем отнять из одной даты другую и посмотреть, сколько это составляет лет. Подумай, как это можно сделать)

Подумал ), не понимаю как посмотреть сколько это лет + мне нужны не только года но и дни и месяцы. Мы отнимаем от текущей даты дату рождения и получаем миллисекунды, что они могут нам дать кроме количества дней.

2023-07-25 05:41 UTC, sergkryk commented on 3-birthday/main.js
> +  const birthday = new Date(Number(year), Number(month) + 1, date);
> Не понял, зачем к месяцу прибавлять 1?

Ошибка

> Я впрниципе не понял, зачем приводить к строке. Можно ж сразу дату распарсить)

Ошибка, притянул из первой функции но там я пароли чтобы год увеличить и получить дату когда покупатель будет взрослый.

В целом эта функция не очень, удалил её и оставил первый вариант. Как по мне он максимально простой и решает задачу в два действия.

2023-07-25 05:53 UTC, sergkryk commented on 3-birthday/main.js
> +  const birthday = new Date(Number(year), Number(month) + 1, date);
> Ты можешь перевести обе даты в timestamp и узнаешь разницу между ними в миллисекундах. 

Что мне дадут миллисекунды в данном случае? Как их применить? Получить количество дней?

> Из этого количества миллисекунд мы уже сможем узнать, сколько лет пользователю и подходит ли он к нужным критериям.

Ещё раз, количество миллисекунд ничего мне не даёт. Если я прибавлю их к дате рождения я получу текущую дату и наоборот. Как мне получить из них количество полных лет? Мне нужен какой-то эталон чтобы сравнить и тогда моя функция сильно увеличивается в сравнении с первым вариантом, где я просто получаю дату "взросления" покупателя и сравниваю с сегодняшней.

2023-07-28 05:04 UTC, Grinv commented on 3-birthday/main.js
> +console.log(isAdultV2('1983-06-07'));
К первому варианту у меня претензий не было.
`isAdultV2` выдавал неверные данные для пограничных состояний)

2023-07-28 05:04 UTC, Grinv commented on 3-birthday/main.js
> +  const birthday = new Date(Number(year), Number(month) + 1, date);
Согласен. Оставим так

2023-07-28 05:05 UTC, Grinv approved these changes

2023-07-28 05:05 UTC, merged