adds 4-timer
sergkryk/purple_js_advanced pull request #6
Opened 2023-07-18 12:53 UTC by sergkryk

2023-07-20 04:34 UTC, Grinv requested changes

2023-07-20 04:34 UTC, Grinv commented on 4-timer/main.js
> +console.log(timeLeft());
Давай уберём отсюда console.log, он тут лишний и отвлекает

2023-07-20 04:34 UTC, Grinv commented on 4-timer/main.js
> +  return el;
👍

2023-07-20 04:34 UTC, Grinv commented on 4-timer/main.js
> +  return `${monthLeft()} месяцев, ${daysLeft()} дней, ${timeLeft()}`;
1) Не очень красиво, что структура не консистентная (не однородная)
У месяцев почему-то добаляется слово тут, у дней тоже. А у времени внутри timeLeft
Давай либо тут добавлять слово у всех счётчиков, либо перенесём у месяцев и дней внутрь monthLeft и daysLeft

2) Я бы переименовал тогда функции в `getMonthLeft`, `getDaysLeft`
3) Не забывай про склонения, нам надо это учитывать. 1 месяЦ, 2 месяЦА, 5 месяЦЕВ. С остальными данными тоже

2023-07-20 04:34 UTC, Grinv commented on 4-timer/main.js
> +  const MONTHS_IN_YEAR = 12;
У тебя константа объявляется каждый раз, когда мы вызываем функцию.
В этом нет необходимости, так как она постоянна и не меняется и я бы вынес её за функцию

2023-07-20 04:34 UTC, Grinv commented on 4-timer/main.js
> +  return DAYS_IN_DECEMBER - currentDay;
Реализация рабочая. Но очень направленная под конкретную дату.
Давай сделаем чуть более универсальной. Представь, что мы должны считать оставшееся время не до конкретно нового года, а до любой даты в этом году, которую ввёл пользователь.
С месяцем будет просто. Но вот с днями нам надо учитывать и 28 и 30 и 31 день и високосный год :)

2023-07-20 04:34 UTC, Grinv commented on 4-timer/main.js
> +  })
Бесконечный счётчик) Нам надо его остановить, как только мы достигнем даты

2023-07-20 17:20 UTC, sergkryk commented on 4-timer/main.js
> +  const MONTHS_IN_YEAR = 12;
исправил

2023-07-22 20:10 UTC, sergkryk commented on 4-timer/main.js
> +  })
исправил

2023-07-22 20:12 UTC, sergkryk commented on 4-timer/main.js
> +  return DAYS_IN_DECEMBER - currentDay;
> Реализация рабочая. Но очень направленная под конкретную дату.
По ТЗ именно так и было поэтому я не стал заморачиваться.

> Давай сделаем чуть более универсальной.
Убил два дня, что-то получилось, но насколько такой код подойдёт под продакшн я не знаю. Хотел бы увидеть готовое решение которое применялось в коммерческих проектах.

2023-07-22 20:12 UTC, sergkryk commented on 4-timer/main.js
> +  return `${monthLeft()} месяцев, ${daysLeft()} дней, ${timeLeft()}`;
добавил отдельную функцию

2023-07-25 02:42 UTC, Grinv requested changes

2023-07-25 02:42 UTC, Grinv commented on 4-timer/main.js
> +// честно украденная функция из интернета для склонения в русском языке
Это нормально)
Для этого существует уже устоявшийся термин plural. Или pluralize
Давай применим нативный метод Intl.PluralRules для этого
Пример реализации можно посмотреть например тут https://2ality.com/2019/12/intl-pluralrules.html

2023-07-25 02:42 UTC, Grinv commented on 4-timer/main.js
> +form.addEventListener("submit", (evt) => {
Лучше либо устояшееся сокращение `e`
Но я предпочитаю писать полностью `event`
evt - это ни туда, ни сюда)

2023-07-25 02:42 UTC, Grinv commented on 4-timer/main.js
> +  const [year, month, date] = formData?.date.split("-");
Почему не просто
```javascript
const [year, month, date] = data.get('date');
```
?

2023-07-25 02:42 UTC, Grinv commented on 4-timer/main.js
> +  const deadline = new Date(year, Number(month) - 1, date);
Я так и не понял, зачем ты отнимаешь месяц и снова создаёшь дату.
Чем не устраивает запись `new Date('2023-07-26')`?

2023-07-26 05:51 UTC, sergkryk commented on 4-timer/main.js
> +  const deadline = new Date(year, Number(month) - 1, date);
Решил более явно создавать дату, скорее всего осталось из начальных набросков и не заметил при рефакторинге который не делал ) т.к. задолбали эти даты. Исправлено.

2023-07-26 05:53 UTC, sergkryk commented on 4-timer/main.js
> +  const [year, month, date] = formData?.date.split("-");
исправил

2023-07-26 05:54 UTC, sergkryk commented on 4-timer/main.js
> +form.addEventListener("submit", (evt) => {
на курсах говорили что норм поэтому так и прижилось, исправил

2023-07-26 06:25 UTC, sergkryk commented on 4-timer/main.js
> +// честно украденная функция из интернета для склонения в русском языке
применил

2023-07-28 05:27 UTC, Grinv requested changes

2023-07-28 05:27 UTC, Grinv commented on 4-timer/main.js
> +      : formatPlural(counter.years, yearPlural)
```javascript
counter.years === 0 ? "" : formatPlural(counter.years, yearPlural)
```
с остальными также

2023-07-28 05:27 UTC, Grinv commented on 4-timer/main.js
> +const pr = new Intl.PluralRules("ru-RU");
Давай всё-таки использовать более понятный нейминг. Всегда думай о том, что после тебя кому-то надо будет читать код и расшифровывать названия данных. Старайся делать код самодокументируемым.
Тут можно назвать например `pluralRules`

2023-07-28 05:27 UTC, Grinv commented on 4-timer/main.js
> +  const suffix = plurals.get(rule);
Достаточно холиварное решение. По мне лучше дополнить обработчик, чем усложнять входящие данные.
Потому что обработчик один, а данных может быть много.
Также часто библиотеки для pluralize похожий интерфейс.
```javascript
function formatPlural(num, [one, few, many]) {
  const rule = pr.select(num);

  switch (rule) {
    case 'one':
      return `${num} ${one}`;
    case 'few':
      return `${num} ${few}`;
    case 'many':
      return `${num} ${many}`;
    default:
      throw new Error(`Unknown: ${rule}`);
  }
}
```
Тогда входящие данные превратятся из 
```javascript
const yearPlural = new Map([
  ["one", "год"],
  ["few", "года"],
  ["many", "лет"],
]);
```
в простое
```javascript
const yearPlural = ['год', 'года', 'лет'];

2023-07-29 14:38 UTC, sergkryk commented on 4-timer/main.js
> +      : formatPlural(counter.years, yearPlural)
исправлено

2023-07-29 14:39 UTC, sergkryk commented on 4-timer/main.js
> +const pr = new Intl.PluralRules("ru-RU");
исправлено

2023-07-31 13:28 UTC, sergkryk commented on 4-timer/main.js
> +  const suffix = plurals.get(rule);
поменял

2023-08-03 09:28 UTC, Grinv approved these changes

2023-08-03 09:28 UTC, Grinv commented on 4-timer/main.js
> +}
👍

2023-08-03 09:28 UTC, merged